/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/pipeline': typeof PipelineRoute
  '/quiz': typeof QuizRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/pipeline': typeof PipelineRoute
  '/quiz': typeof QuizRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/pipeline': typeof PipelineRoute
  '/quiz': typeof QuizRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/glossary'
    | '/pipeline'
    | '/quiz'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/glossary'
    | '/pipeline'
    | '/quiz'
    | '/chapters/$slug'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/pipeline'
    | '/quiz'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  PipelineRoute: typeof PipelineRoute
  QuizRoute: typeof QuizRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  PipelineRoute: PipelineRoute,
  QuizRoute: QuizRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
